name: Pull Request Checks

on:
  - pull_request

jobs:
  spellcheck:
      name: Spellcheck
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v3
        - uses: rojopolis/spellcheck-github-actions@0.47.0
          name: Spellcheck
          with:
            config_path: .spellcheck/spellcheck.yml # put path to configuration file here
            task_name: Markdown
  build:
    name: Tox Build Checks
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox -v